{
 "title": "DBaaS metrics",
 "description": "Core DBaaS metrics for monitoring performance and stability during Day-2 operations.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_static{pg_cluster=\"hippo\"}",
     "legendFormat": "{{ short_version }}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{pg_cluster=\"hippo\"}",
     "legendFormat": "{{ short_version }}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"hippo\"})",
     "legendFormat": "{{ short_version }}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccp_database_size_bytes{dbname=\"hippo\"}\r",
     "legendFormat": "{{ dbname }} ({{ instance}})"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccp_nodemx_data_disk_available_bytes{mount_point=\"/pgdata\"}",
     "legendFormat": "{{ dbname }} ({{ instance}})"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{name=\"hippo\"}* 1000"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Number of transactions in this database that have been committed per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "irate(ccp_stat_database_xact_commit{dbname=\"hippo\"}[15s])\r",
     "legendFormat": "{{ dbname }} ({{ instance}})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Length of time in seconds of the longest idle in transaction session ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "ccp_connection_stats_max_idle_in_txn_time\r*10",
     "legendFormat": "{{ kubernetes_name}} {{ instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Average utilization of CPU in percentage [0-100]%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{kops_k8s_io_instancegroup=\"hippo-nodes\", pod=~\"hippo.*\", pod!~\"hippo-backrest.*\", container=\"database\"}[60s]) * 100",
     "legendFormat": "{{ pod }} CPU Usage [%]"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{kops_k8s_io_instancegroup=\"hippo-nodes\", pod=~\"hippo.*\", pod!~\"hippo-backrest.*\", container=\"database\"}",
     "legendFormat": "{{ pod }} Memory Usage"
    }
   ]
  },
  {
   "title": "Disk Reads per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "Disk Reads" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{kops_k8s_io_instancegroup=\"hippo-nodes\", pod=~\"hippo.*\", device!~\"/dev/nvme0n1\", pod!~\"hippo-backrest.*\", container=\"database\"}[60s])",
     "legendFormat": "{{ pod }} Disk reads/second"
    }
   ]
  },
  {
   "title": "Disk Writes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "Disk Writes" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{kops_k8s_io_instancegroup=\"hippo-nodes\", pod=~\"hippo.*\", device!~\"/dev/nvme0n1\", pod!~\"hippo-backrest.*\", container=\"database\"}[60s])",
     "legendFormat": "{{ pod }} Disk Writes/second"
    }
   ]
  },
  {
   "title": "Network Receive Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Network Receive Rate" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{kops_k8s_io_instancegroup=\"hippo-nodes\", pod=~\"hippo.*\", pod!~\"hippo-backrest.*\"}[60s])",
     "legendFormat": "{{ pod }} Receive Rate"
    }
   ]
  },
  {
   "title": "Network Transmit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Network Transmit Rate" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{kops_k8s_io_instancegroup=\"hippo-nodes\", pod=~\"hippo.*\", pod!~\"hippo-backrest.*\"}[60s])",
     "legendFormat": "{{ pod }} Transmit Rate"
    }
   ]
  }
 ]
}