apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: trpawlows@gmail.com
    privateKeySecretRef:
      name: acme-letsencrypt-production
    solvers:
    - selector:
      http01:
        ingress:
          class: nginx