apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-cert
  namespace: pgo
spec:
  issuerRef:
    name: acme-letsencrypt-production
    kind: ClusterIssuer
  secretName: pgadmin-tls
  dnsNames:
  - pgadmin4.k8s.retipuj.com